# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98c7f06bb4e9b86f70e2638e2d94f3a91f6c57c027ffb469dba565cc759d99a2bfccf9be39913c7e6076655a19c011436253bbe0aff09ad51d829241480ed0fd

test:
  secret_key_base: 7b9fc83b265707efeaeebbff4817fb5ffef5734ec8b0348ea5ee9815ae270c45df887cbbccc278b5a6dd6c926940d885bd2a38cbb2eb3c615b6ace8f37bc3462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
